config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[show]
  resources :games do
    resources :orders, only: %i[new create]
  end

  resources :orders, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  CATEGORY = %w[FPS Moba RPG MMO MMORPG Action Adventure Puzzle Sports Strategy Simulation Horror].freeze
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :category, presence: true, inclusion: { in: CATEGORY }
  validates :user_id, presence: true
  validates :image, presence: true
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :orders, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_game, only: %i[show edit update destroy]

  def index
    if params[:search].present?
      @games = Game.where("name ILIKE ?", "%#{params[:search]}%")
      @games = @games.where(bought: false)
    elsif params[:category].present?
      @games = Game.where(category: params[:category], bought: false)
    else
      @games = Game.where(bought: false)
    end
  end

  def new
    @game = Game.new
  end

  def create
    # We need to create a new game using the current user
    @game = Game.new(game_params)
    @game.user = @user

    if @game.save
      redirect_to game_path(@game)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = current_user
    @order = Order.new
  end

  def edit; end

  def update
    @game.update(game_params)
    redirect_to games_path(@games)
  end

  def destroy
    @game.destroy
    redirect_to games_path notice: "Game was successfully destroyed.", status: :see_other
  end

  def bought?
    @game.bought
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def authenticate_user!
    redirect_to new_user_session_path unless user_signed_in?
    @user = current_user
  end

  def game_params
    params.require(:game).permit(:name, :description, :price, :category, :user_id, :image, :bought)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: %i[new create index show]
  before_action :set_game, only: %i[new create]

  def new
    @order = Order.new
  end

  def index
    @games_sold = Game.where(bought: true, user_id: current_user)
    @games_listed = Game.where(bought: false, user_id: current_user)
    @orders = Order.all.select { |m| m.user_id == current_user.id }
  end

  def create
    @order = Order.new
    @order.user = current_user
    @order.game = @game
    if @order.save
      @game.bought = true
      @game.save
      redirect_to @order
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @order = Order.find params[:id]
  end


  private

  def set_game
    @game = Game.find(params[:game_id])
  end

  def authenticate_user!
    redirect_to new_user_session_path unless user_signed_in?
    @user = current_user
  end

  def order_params
    params.require(:order).permit(:game_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @games = Game.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/edit.html.erb
 <div class="container w-50">
    <div class="col-12">
      <h2 class="text-center my-5">Edit Listing</h2>
      <%= simple_form_for(@game) do |f| %>
        <div class="row"><%= f.input :name, placeholder: "Enter game name" %></div>
        <div class="row"><%= f.input :description %></div>
        <div class="row">
          <div class="col-6"><%= f.input :category, collection: Game::CATEGORY, prompt: "Select a category" %></div>
          <div class="col-6"><%= f.input :price, placeholder: "$ 9999"  %></div>
        </div>
        <div class="row"><%= f.input :image, label: false, as: :file, cloudinary: { resource_type: :image, tags: ['post_picture'] } %></div>
        <%= link_to games_path do%>
          <button class="bot-purple me-2"><i class="fa-solid fa-arrow-left fa-2xs"></i> Back</button>
        <% end %>
        <%= f.submit class: 'bot-yellow yellow' %>
      <% end %>
    </div>
  </div>

app/views/games/index.html.erb
<div class="container mt-3">  
  <h1 class="text-center">Games Listings</h1>
  <div class="row mt-3">
  <% if @games.empty? %>
    <div class="d-flex justify-content-center">
      <div>
        <h3 class="text-center text-danger">Game not found!</h3>
        <%= image_tag "mario-bg.png"%>
      </div>
    </div>
  <% else  %>
    <% @games.each do |game| %>

      <div class="col-md-3 mb-2">
        <div class="product-card">
          <%= link_to game_path(game), class:"text-decoration-none" do %>
            <div class="product-image-container">
              <%= cl_image_tag game.image.key %>
            </div>
            <div class="d-flex flex-column full-height justify-content-between product-details">
              <p class="product-name"><%= game.name %></p>
              <p class="product-price">$<%= game.price %></p>
            </div>
          <%end%>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/games/new.html.erb
  <div class="container w-50">
    <div class="col-12">
      <h2 class="text-center my-5">New Listing</h2>
      <%= simple_form_for(@game) do |f| %>
        <div class="row"><%= f.input :name, placeholder: "Enter game name" %></div>
        <div class="row"><%= f.input :description %></div>
        <div class="row">
          <div class="col-6"><%= f.input :category, collection: Game::CATEGORY, prompt: "Select a category" %></div>
          <div class="col-6"><%= f.input :price, placeholder: "$ 9999"  %></div>
        </div>
        <div class="row"><%= f.input :image, label: false, as: :file, cloudinary: { resource_type: :image, tags: ['post_picture'] } %></div>
        <%= link_to games_path do%>
          <button class="bot-purple me-2"><i class="fa-solid fa-arrow-left fa-2xs"></i> Back</button>
        <% end %>
        <%= f.submit class: 'bot-yellow yellow' %>
      <% end %>
    </div>
  </div>

app/views/games/show.html.erb
<div class="m-3">
  <%= link_to games_path do%>
    <button class="bot-purple"><i class="fa-solid fa-arrow-left fa-2xs"> Back</i></button>
  <% end %>
</div>
<div class="container mt-3">
  <div class="row">
    <div class="col-5">
      <%= cl_image_tag @game.image.key, width: 400 %>
    </div>
    <div class="col-6">
      <h1><%= @game.name %></h1>
      <p>Description: <%= @game.description %></p>
      <p>Category: <%= @game.category %></p>
      <p>Price: $<%= @game.price %></p>
      <% if @user == @game.user %>
        <% unless @game.bought? %>
          <%= link_to edit_game_path(@game), class: "text-decoration-none" do%>
            <button class="bot-yellow-edit yellow me-2"><i class="fa-solid fa-pen-to-square"></i> Edit</button>
          <% end %>
          <%= link_to game_path(@game), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
            <button class="bot-red red"><i class="fa-solid fa-trash fa-fa"></i> Delete</button>
          <% end %>
        <% end %>
      <% else %>
        <% unless @game.bought? %>
          <%= link_to new_game_order_path(game_id: @game.id) do%>
            <button class="bot-yellow yellow"><i class="fa-solid fa-cart-shopping"> Buy</i></button>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buy and Sell games here - GamesKaar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="shortcut icon" href="<%= asset_path('favicon.png') %>" type="image/x-icon" />
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
   <div data-controller="scroll-to-top">
  <a href="#" class="scroll-to-top" data-action="click->scroll-to-top#scrollToTop" data-scroll-to-top-target="button"><i class="fa-solid fa-arrow-up fa-bounce" style="color: #ffc600;"></i></a>
</div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container mt-5">
  <%= render "orders/shared/bought" %>
  <hr>
  <div class="row mt-3">
    <div class="col-md-6" style="border-right: solid;">
      <%= render "orders/shared/listed" %>
    </div>

    <div class="col-md-6">
      <%= render "orders/shared/sold" %>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <div class="card border-0">
        <div class="d-flex card-category">
          <%= cl_image_tag @game.image.key, class: "img-fluid img-small" %>
          <div class="text-start my-2">
            <strong><span class="card-text mx-3"><%= @game.name %></span></strong>
            <p class="mx-3 my-2"><%= @game.description %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card border-0">
        <div class="card-body card-category" data-controller="apply-discount">
          <p class="card-text" data-target="apply-discount.price" data-initial-price="<%= @game.price %>">
            <strong>Price: <%= number_to_currency(@game.price) %></strong>
          </p>
          <%= simple_form_for([@game, @order], data: { action: "keyup->apply-discount#count" }, html: { class: "mt-3" }) do |f| %>
            <div class="row">
                <%= f.label :coupon do %>
                  Promo Code <i class="fa-solid fa-receipt text-danger"></i>
                <% end %>
                <div class="col-4 my-2">
                  <%= f.input :coupon, label: false, placeholder: "Add your coupon code", input_html: { data: { target: "apply-discount.input" } }, class: "form-control" %>
                </div>
            </div>
            <p class="card-text text-end" data-apply-discount-target="discount">Discount: <%= number_to_currency(0) %></p>
            <p class="card-text text-end" data-apply-discount-target="finalPrice"><strong>Total: <%= number_to_currency(@game.price) %></strong></p>
            <div class="d-flex justify-content-end">
              <%= link_to games_path, class: "me-2 bot-purple" do %>
                <i class="fa-solid fa-arrow-left fa-2xs"></i> Back
              <% end %>
              <%= f.submit 'Confirm order', class: "bot-yellow" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/shared/_bought.erb
  <h1 class="text-center">My Game Library</h1>
  <div class="row mt-3">
    <% @orders.each do |order| %>
      <div class="col-md-2">
        <div class="card card-category mb-2">
          <div class="mb-2">
            <%= cl_image_tag order.game.image.key, class: "card-img-top" %>
          </div>
          <div class="" style="height: 50px;">
            <h5 class="card-title text-center">
              <%= link_to order.game.name, order_path(order), class: "text-decoration-none" %>
            </h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/orders/shared/_listed.erb
  <h1 class="text-center">My Listed Games</h1>
  <div class="row">
    <% @games_listed.each do |game| %>
      <div class="col-md-4">
        <div class="card card-category mb-2">
          <div class="mb-2">
            <%= cl_image_tag game.image.key, class: "card-img-top" %>
          </div>
          <div class="" style="height: 50px;">
            <h5 class="card-title text-center">
              <%= link_to game.name, game_path(game), class: "text-decoration-none" %>
            </h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/orders/shared/_sold.erb
  <h1 class="text-center">My Sold Games</h1>
  <div class="row">
    <% @games_sold.each do |game| %>
      <div class="col-md-4">
        <div class="card card-category">
          <div class="mb-2">
            <%= cl_image_tag game.image.key, class: "card-img-top" %>
          </div>
          <div class="" style="height: 50px;">
            <h5 class="card-title text-center">
              <%= link_to game.name, game_path(game), class: "text-decoration-none" %>
            </h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/orders/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div class="card card-category">
        <%= cl_image_tag @order.game.image.key, class: "card-img-top" %>
        </div>
        <div class="card-body mt-3">
          <h3 class="card-title text-center"><%= @order.game.name %></h3>
          <p class="card-text"><strong>Description:</strong> <%= @order.game.description %></p>
          <p class="card-text"><strong>Category:</strong> <%= @order.game.category %></p>
        </div>
    </div>
  </div>
  <div class="row mt-3 mb-2">
    <div class="col text-center">
      <%= link_to orders_path do%>
        <button class="bot-purple"><i class="fa-solid fa-arrow-left fa-2xs"> Back</i></button>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "banners/banner-5.png", class:"w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "banners/banner-2.png", class:"w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "banners/banner-3.png", class:"w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "banners/banner-4.png", class:"w-100" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<h1 class="text-center my-5">FEATURED GAMES</h1>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="featured-banner1 card h-100">
        <div class="d-flex justify-content-center align-items-center" style="height: 400px;">
           <h1 class=""><%= link_to "Add your favorite game to sell", new_game_path, class:"link-text text-decoration-none text-white"%></h1>
        </div>
      </div>
    </div>
    <div class="col-md-6">
    <div class="featured-banner2 card h-100">
        <div class="d-flex justify-content-center align-items-center" style="height: 400px;">
           <h1 class=""><%= link_to "Check our store!", games_path, class:"link-text text-decoration-none text-white" %></h1>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-black text-center text-white">
  <!-- Grid container -->
  <div class="container pb-3">
    <!-- Section: Social media -->
    <section class="mt-2">
    <!-- Rafa -->
      <a
        title="Rafael"
        target="_blank"
        class="btn text-white btn-floating m-1 social-icon"
        style="background-color: #ff3b4e;"
        href="https://github.com/rafteodoro"
        role="button"
        ><i class="fa-brands fa-github"></i
      ></a>

      <!-- lu -->
      <a
        title="Lu"
        target="_blank"
        class="btn text-white btn-floating m-1 social-icon"
        style="background-color: #E900FF;"
        href="https://github.com/darkwings28"
        role="button"
        ><i class="fa-brands fa-github"></i
      ></a>

      <!-- kaique -->
      <a
        title="Kaique"
        target="_blank"
        class="btn text-white btn-floating m-1 social-icon"
        style="background-color: #5800ff;"
        href="https://github.com/nagato94"
        role="button"
        ><i class="fa-brands fa-github"></i
      ></a>
      <!-- alyson -->
      <a
        title="Alyson"
        target="_blank"
        class="btn text-white btn-floating m-1 social-icon"
        style="background-color: #ffc600;"
        href="https://github.com/AlysonPereira"
        role="button"
        ><i class="fa-brands fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->

  </div>
<p class="text-white-50 mt-1">&copy;2023 GamesKaar | All Rights Reserved</p>
  <!-- Copyright -->

  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="top">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand me-3" do %>
        <%= image_tag "logo.png", class: "mb-2 me-2" %> <span class="logo-font">GamesKaar</span>
      <% end %>

      <%= form_with url: "/games", method: :get, class: "d-flex mb-0" do |form| %>
        <%= form.text_field :search, class: "form-control me-2 col-6", style: "width: 600px", placeholder: "Search for any game..." %>
        <%= form.submit "Search", class:"bot-outline"%>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
          <li class="btn-group m-2 dropdown">
            <button class="bot-outline dropdown-toggle text-decoration-none " type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </button>
            <div class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "All", games_path, class: "dropdown-item fw-bold" %>
              <%= link_to "Action", games_path(category: "Action"), class: "dropdown-item" %>
              <%= link_to "Adventure", games_path(category: "Adventure"), class: "dropdown-item" %>
              <%= link_to "FPS", games_path(category: "FPS"), class: "dropdown-item" %>
              <%= link_to "Horror", games_path(category: "Horror"), class: "dropdown-item" %>
              <%= link_to "MMO", games_path(category: "MMO"), class: "dropdown-item" %>
              <%= link_to "MMORPG", games_path(category: "MMORPG"), class: "dropdown-item" %>
              <%= link_to "MOBA", games_path(category: "MOBA"), class: "dropdown-item" %>
              <%= link_to "Puzzle", games_path(category: "Puzzle"), class: "dropdown-item" %>
              <%= link_to "RPG", games_path(category: "RPG"), class: "dropdown-item" %>
              <%= link_to "Simulation", games_path(category: "Simulation"), class: "dropdown-item" %>
              <%= link_to "Sports", games_path(category: "Sports"), class: "dropdown-item" %>
              <%= link_to "Strategy", games_path(category: "Strategy"), class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item m-2 py-2">
            <%= link_to "New listing", new_game_path, class: "bn5 text-decoration-none" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item mt-3 me-2 ms-2 dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <i class="fa-solid fa-circle-user fa-2xl text-white-50"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Library", orders_path, class: "dropdown-item" %>
              <%= link_to "Store", games_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item m-2">
            <%= link_to "Login", new_user_session_path, class: "bot-outline nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>